### ISSUE TITLE
sbt +compile failed

### ISSUE THREAD

**Issue by PhilAndrew** [arturopala/cross-scala.g8#1]
Dos

[info] compiling 1 Scala source to D:\home\projects\philtest\cross-scala\.jvm\target\scala-2.11\classes ...
[info] Non-compiled module 'compiler-bridge_2.11' for Scala 2.11.12. Compiling...
[info]   Compilation completed in 17.1s.
[error] java.nio.channels.OverlappingFileLockException
[error]         at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
[error]         at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
[error]         at java.base/sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1109)
[error]         at java.base/java.nio.channels.FileChannel.lock(FileChannel.java:1063)
[error]         at lmcoursier.internal.shaded.coursier.paths.CachePath.withStructureLock(CachePath.java:144)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withStructureLock(CacheLocks.scala:21)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:38)
[error]         at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.remote(Downloader.scala:382)
[error]         at lmcoursier.internal.shaded.coursier.cache.internal.Downloader.$anonfun$remote$5(Downloader.scala:480
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] (rootNative / update) java.nio.channels.OverlappingFileLockException
[error] Total time: 32 s, completed 19 May 2022, 3:46:49 pm

**Comment by PhilAndrew** [comment]
On second try it went away. Dos windows
